### ISSUE TITLE
Drop old Nodejs version support?

### ISSUE THREAD

**Issue by hasezoey** [mongoosejs/mpath#17]
**Do you want to request a *feature* or report a *bug*?**
discussion

**What is the current behavior?**
Currently the code seems to be made for newer version of nodejs, while a effort was made to be nodejs 4.x compatible, but did not reach everywhere (like `stringToParts.js` is still let/const), so maybe consider dropping old version of nodejs (either by matching what mongoose requires or something like nodejs 8)

PS: it also seems old version are not even tested anymore (lowest version i see is 12)

**Comment by vkarpov15** [comment]
If memory serves, `let` and `const` work fine in Node 4 as long as you use strict mode. So that's not a problem.

But you're right that we should drop support for older versions of Node. No need to support anything below 12 these days. I'd like to do that before we ship a 1.0.0 release.
